require.config({
    baseUrl: "Scripts",
    paths: {

        'application': '/App/app',
        'jquery.min': 'kendoUI/js/jquery.min',
        'angular.min': 'kendoUI/js/angular.min',
        'jquery.min': 'jsV3/jquery.min',
        // 'angular.min': 'jsV3/angular.min',


        'jqueryUi': '/bower_components/jquery-ui/jquery-ui.min',
        //  'jquery-plugin': 'captcha/jquery.plugin.min',
        //  'jquery-realperson': 'captcha/jquery.realperson.min',
        'angular-ui-route': 'angular-ui/angular-ui-router.min',
        'angularAMD': 'core/angularAMD',
        'ui-bootstrapTemep': 'angular-ui/bootstrap.min',
        'ui-bootstrap': 'angular-ui/ui-bootstrap-tpls.min',
        'blockUI': 'angular-ui/angular-block-ui.min',
        'ncy-angular-breadcrumb': 'angular-ui/angular-breadcrumb.min',
        'ngload': 'core/ngload',
        'jszip': 'kendoUI/js/jszip.min',
        'kendo.web.min': 'kendoUI/js/kendo.web.min',
        'kendoUi': 'kendoUI/js/kendo.core.min',
        'kendo.dataviz.core.min': 'kendoUI/js/kendo.dataviz.core.min',
        'kendo.dataviz.themes.min': 'kendoUI/js/kendo.dataviz.themes.min',
        'kendo.dataviz.chart.min': 'kendoUI/js/kendo.dataviz.chart.min',
        'kendoGridFa': 'kendoUI/js/messages/kendo.messages.fa-IR',
        'dateFa': 'kendoUI/js/cultures/kendo.culture.fa-IR.min',
        'kendoAngular': 'kendoUI/js/kendo.angular.min',
        'jalaliDate': 'date/JalaliDate',
        'moment': 'date/moment.min',
        'momentJalaali': 'date/moment-jalaali',
        'animate': 'animate/angular-animate',
        'angular-sanitize': 'core/angular-sanitize',
        'toastr': 'angular-ui/toastr',
        'fileModel': 'angular-ui/angular-file-model',
        'leaflet': 'leaflet/leaflet',
        'geocoder': 'leaflet/Control.Geocoder',

        'combo': '/App/hesabfa-combobox',
        'scrollbar': '/App/hesabfa-scrollbar',
        'helper': '/App/helper',
        //'bootstrapjs': '/bootstrap/js/bootstrap.min',
        'dx': 'dx/dx.all',
        'dxFa': 'dx/dx.messages.fa',
        'roweditor': '/App/roweditor',
        'preApp': '/App/preApp',
        'gridHelper': '/App/gridHelper',
        'printReports': '/App/printReports',
        'maskedinput': 'jquery.maskedinput.min',
        //Directive
        'captchaImage': '/App/directive/captchaImage',
        'infoWindow': '/App/directive/infoWindow',
        'buttonValidation': '/App/directive/buttonValidation',
        'googleMap': '/App/directive/googleMap',
        'textEmail': '/App/directive/textEmail',
        'textNumeric': '/App/directive/textNumeric',
        'textNumericChar': '/App/directive/textNumericChar',
        'textNationalCode': '/App/directive/textNationalCode',
        'windowRedirect': '/App/directive/windowRedirect',
        'autoComplete': '/App/directive/autoComplete',
        'comboCity': '/App/directive/comboCity',
        'textNumericEslash': '/App/directive/textNumericEslash',
        'cartable': '/App/directive/cartable',
        'cartableVerificationForm': '/App/directive/cartableVerificationForm',
        'treeList': '/App/directive/treeList',
        'checkTreeList': '/App/directive/checkTreeList',
        'treeDropDown': '/App/directive/treeDropDown',
        'leafletMap': "/App/directive/leafletMap",


        'editItem': '/App/directive/editItem',
        'editContact': '/App/directive/editContact',
        'nodeSelect': '/App/directive/nodeSelect',
        'vahedSelect': '/App/directive/vahedSelect',
        'noeEjareSelect': '/App/directive/noeEjareSelect',
        'noeSazeSelect': '/App/directive/noeSazeSelect',
        'goroheSazeSelect': '/App/directive/goroheSazeSelect',
        'editBank': '/App/directive/editBank',
        'editCash': '/App/directive/editCash',
        'dateRange': '/App/directive/dateRange',
        'editSaze': '/App/directive/editSaze',
        'datePicker': '/App/directive/datePicker',
        'decimalPointZero': '/App/directive/decimalPointZero',
        'displayNumbers': '/App/directive/displayNumbers',
        'editAccount': '/App/directive/editAccount',
        'editDetailaccount': '/App/directive/editDetailaccount',
        'empty': '/App/directive/empty',
        'finanAccountSelect': '/App/directive/finanAccountSelect',
        'floatPositive': '/App/directive/floatPositive',
        'inputCode': '/App/directive/inputCode',
        'inputDate': '/App/directive/inputDate',
        'inputFloat': '/App/directive/inputFloat',
        'inputInteger': '/App/directive/inputInteger',
        'inputMoney': '/App/directive/inputMoney',
        'inputMoneyPercent': '/App/directive/inputMoneyPercent',
        'inputText': '/App/directive/inputText',
        'integerPositive': '/App/directive/integerPositive',
        'itemSelectTree': '/App/directive/itemSelectTree',
        'keyboardFilter': '/App/directive/keyboardFilter',
        'money': '/App/directive/money',
        'ngEnter': '/App/directive/ngEnter',
        'ngRightClick': '/App/directive/ngRightClick',
        'onEnter': '/App/directive/onEnter',
        'selectOnClick': '/App/directive/selectOnClick',
        'sendComment': '/App/directive/sendComment',
        'smsEditor': '/App/directive/smsEditor',
        'editCost': '/App/directive/editCost',
        'processWorkFlow': '/App/directive/processWorkFlow',
        'editChap': '/App/directive/editChap',
        'editChapkhaneh': '/App/directive/editChapkhaneh',
        'editPersonel': '/App/directive/editPersonel',
        'editNoeChap': '/App/directive/editNoeChap',
        'editReservation': '/App/directive/editReservation',
        'editContractStop': '/App/directive/editContractStop',
        
        //'alert': '/App/directive/alert',
        //Filter
        'digitGroup': '/App/filters/digitGroup',
        'number': '/App/filters/number',
        "trustHtml": "/App/filters/trustHtmlFilter",
        //"persianDateTime": "/App/filters/persianDateTimeFilter",
        //"trustHtml": "/App/filters/trustHtmlFilter",

        // services
        'dataService': '/App/services/DataService',
        'messageService': '/App/services/MessageService',
        'dateService': '/App/services/DateService',
        'validatorsService': '/App/services/ValidatorsService',
        'redirectService': '/App/services/RedirectService',

        //Factory
        "commandFactory": "/App/factories/commandFactory",
        "helperFactory": "/App/factories/helperFactory",
        'angularjs-gauge': 'angular-ui/angularjs-gauge',
        'pdfmake': "makePdf/vfs_fonts",
        'pdfMakeLib': "makePdf/pdfmake"

    },
    shim: {
        'jquery.min': { exports: "$" },
        'angular.min': { deps: ["jquery.min"], exports: "angular" },
        'angularAMD': ['angular.min'],
        'ngload': ['angularAMD'],
        'leaflet': { exports: 'L' },
        'geocoder': { deps: ["leaflet"] },
        'angular-ui-route': ['angular.min'],
        'blockUI': ['angular.min'],
        'ncy-angular-breadcrumb': { deps: ['angular.min', 'jquery.min'] },
        'angular-sanitize': ['angular.min'],
        'ui-bootstrapTemep': { deps: ['angular.min', 'jquery.min'] },
        'ui-bootstrap': { deps: ['angular.min', 'jquery.min'] },
        'jalaliDate': { deps: ['jquery.min'] },
        'kendo.web.min': { deps: ['jquery.min', 'angular.min', 'jalaliDate'] },
        'kendoUi': { deps: ['jquery.min', 'angular.min', 'jalaliDate', 'jszip', 'kendo.web.min'], exports: "kendoUi" },
        'kendo.dataviz.core.min': { deps: ['kendoUi'] },
        'kendo.dataviz.themes.min': { deps: ['kendo.dataviz.core.min'] },
        'kendo.dataviz.chart.min': { deps: ['kendo.dataviz.themes.min'] },
        'dateFa': { deps: ['kendo.dataviz.chart.min'] },
        'kendoGridFa': { deps: ['dateFa'], exports: "kendoGridFa" },

        'animate': { deps: ['jquery.min', 'angular.min'] },
        'toastr': { deps: ['jquery.min'] },
        'jquery-plugin': { deps: ['jquery.min'] },
        'jquery-realperson': { deps: ['jquery-plugin'] },
        'momentJalaali': { deps: ['jquery.min', 'angular.min', 'moment'] },
        //'lightBox': { deps: ['jquery.min'] },
        'nodeSelect': { deps: ['jquery.min', 'jqueryUi'] },
        'editItem': { deps: ['jquery.min', 'jqueryUi'] },
        'editContact': { deps: ['jquery.min', 'jqueryUi'] },
        //'bootstrapjs': { deps: ['jquery.min', 'jqueryUi'] },
        'maskedinput': { deps: ['jquery.min'] },

        'dx': { deps: ['jquery.min', 'angular.min'] },
        'dxFa': { deps: ['jquery.min', 'angular.min', 'dx'] }
    },
    waitSeconds: 0,
    deps: ['application']
});

require(['jquery.min', 'jszip', 'angular.min', 'ui-bootstrapTemep', 'ui-bootstrap', 'download'], function ($, jszip) {
    window.JSZip = jszip;

    //$(window).on("unload", function () {
    //    var url = $("#stateChangeStart").val();
    //    if (url) {
    //        $.ajax({ type: "POST", url: "/app/api/AuthenticateUrl/SetUrl", data: { Url: url }, async: false });
    //    }
    //});
}); 